### PR TITLE
Support deploy to Tomcat in App Service Linux

### PR DESCRIPTION
**Pull request by ArchangelSDY**

### CODE REVIEW

**Comment by ArchangelSDY** [comment]
@selvasingh

**Comment by yuwzho** [comment]
I don't know the context, but seems it need to merge into another branch like `tomcat`, instead of the basic master branch. Need Asir's information. @selvasingh

**Comment by selvasingh** [comment]
These changes are already in a tomcat branch. See https://github.com/Microsoft/todo-app-java-on-azure/tree/tomcat-on-azure-app-service-linux

**Comment by ArchangelSDY** [comment]
I see. Then only Jenkinsfile should be updated.

**Comment by yuwzho** [comment]
@selvasingh Would you please have a try and merge it?

**Pull request merged**
